// Generated from: feature\Dashboard.feature
import { test } from "../../fixtures/fixture.js";

test.describe('Login with credentials', () => {

  test.beforeEach('Background', async ({ Given, dbPage, When, Then }) => {
    await Given('user navigates to the login page', null, { dbPage }); 
    await When('user clicks the sign in button on the homepage', null, { dbPage }); 
    await When('user fills the username field with credentials from env', null, { dbPage }); 
    await When('the user fills the password field with credentials from env', null, { dbPage }); 
    await When('the user clicks the login button', null, { dbPage }); 
    await Then('the user should be logged in successfully', null, { dbPage }); 
  });
  
  test('Verify User lands on the medical dashboard', async ({ Given, dbPage, When, Then }) => { 
    await Given('the user should be logged in successfully', null, { dbPage }); 
    await When('The user is directed to the dashboard URL', null, { dbPage }); 
    await Then('The page should have URL visible', null, { dbPage }); 
  });

  test('Verify User starts a new assessment', async ({ Given, dbPage, When, Then }) => { 
    await Given('The user is on the dashboard', null, { dbPage }); 
    await When('The user clicks on the "Start New Assessment" button', null, { dbPage }); 
    await Then('the user should be logged in successfully', null, { dbPage }); 
  });

  test('Verify User able to View previous medical assessments', async ({ Given, dbPage, When, Then }) => { 
    await Given('The user is on the dashboard', null, { dbPage }); 
    await When('The user clicks the "View Previous Assessments" button', null, { dbPage }); 
    await Then('The user should be in "View Previous Assessments" page', null, { dbPage }); 
  });

  test('verify User is able See current "AI analysis usage"', async ({ Given, dbPage, When, Then }) => { 
    await Given('The user is on the dashboard', null, { dbPage }); 
    await When('dashboard is displayed with \'AI analysis usage\'', null, { dbPage }); 
    await Then('The page should have URL visible', null, { dbPage }); 
  });

  test('verify User is able See current "upgrade to premium"', async ({ Given, dbPage, When, Then }) => { 
    await Given('The user is on the dashboard', null, { dbPage }); 
    await When('verify user is able click on \'upgrade to premium\' button', null, { dbPage }); 
    await Then('user is on subscription page', null, { dbPage }); 
  });

  test('verify User is able to click current Start your first assessment', async ({ Given, dbPage, When, Then }) => { 
    await Given('The user is on the dashboard', null, { dbPage }); 
    await When('The user clicks on  the Start your first assessment button', null, { dbPage }); 
    await Then('the user should be logged in successfully', null, { dbPage }); 
  });

  test('verify User is able See current "Account Settings"', async ({ Given, dbPage, When, Then }) => { 
    await Given('The user is on the dashboard', null, { dbPage }); 
    await When('The user clicks on Update settings under the Account Settings section', null, { dbPage }); 
    await Then('The user should directed to Account Settings page', null, { dbPage }); 
  });

  test('verify User is able See current Subscription Plans', async ({ Given, dbPage, When, Then }) => { 
    await Given('The user is on the dashboard', null, { dbPage }); 
    await When('The user clicks on Upgrade now  section   in the Subscription Plans section', null, { dbPage }); 
    await Then('user is on subscription page', null, { dbPage }); 
  });

  test('verify User is able See current Assessment History', async ({ Given, dbPage, When, Then }) => { 
    await Given('The user is on the dashboard', null, { dbPage }); 
    await When('The user clicks on View history  section in the Assessment History section', null, { dbPage }); 
    await Then('The user should be in "View Previous Assessments" page', null, { dbPage }); 
  });

  test('verify User is able See current "About Us"', async ({ Given, dbPage, When, Then }) => { 
    await Given('The user is on the dashboard', null, { dbPage }); 
    await When('The user clicks on "About Us  "section   in the "company" section', null, { dbPage }); 
    await Then('The user should directed to "About Us "page', null, { dbPage }); 
  });

  test('verify User is able See current "Blog"', async ({ Given, dbPage, When, Then }) => { 
    await Given('The user is on the dashboard', null, { dbPage }); 
    await When('The user clicks on "Blog  "section   in the "company" section', null, { dbPage }); 
    await Then('The user should directed to "Blog"page', null, { dbPage }); 
  });

  test('verify User is able See current "Contact Us"', async ({ Given, dbPage, When, Then }) => { 
    await Given('The user is on the dashboard', null, { dbPage }); 
    await When('The user clicks on "Contact Us  "section   in the "company" section', null, { dbPage }); 
    await Then('The user should directed to "Contact Us"page', null, { dbPage }); 
  });

  test('verify User is able See current "Terms"', async ({ Given, dbPage, When, Then }) => { 
    await Given('The user is on the dashboard', null, { dbPage }); 
    await When('The user clicks on "Terms "section   in the "© 2025 Manan - Medical Triage Assistant" section', null, { dbPage }); 
    await Then('The user should directed to "Terms"page', null, { dbPage }); 
  });

  test('verify User is able See current "Privacy"', async ({ Given, dbPage, When, Then }) => { 
    await Given('The user is on the dashboard', null, { dbPage }); 
    await When('The user clicks on "Privacy "section   in the "© 2025 Manan - Medical Triage Assistant" section', null, { dbPage }); 
    await Then('The user should directed to "Privacy"page', null, { dbPage }); 
  });

  test('Verify user is able to logout successfully', async ({ Given, dbPage, When, Then }) => { 
    await Given('The user is on the dashboard', null, { dbPage }); 
    await When('The user clicks User profile icon and clicks Logout option', null, { dbPage }); 
    await Then('The user should get "Session Ended" message and rediected to Manan signin Page', null, { dbPage }); 
  });

  test('Verify user is able to directed to settings successfully', async ({ Given, dbPage, When, Then }) => { 
    await Given('The user is on the dashboard', null, { dbPage }); 
    await When('The user clicks User profile icon and clicks  settings option', null, { dbPage }); 
    await Then('The user should directed to "settings"page', null, { dbPage }); 
  });

  test('Verify user is able to directed to Previous Assessments successfully', async ({ Given, dbPage, When, Then }) => { 
    await Given('The user is on the dashboard', null, { dbPage }); 
    await When('The user clicks User profile icon and clicks previous assessment option', null, { dbPage }); 
    await Then('The user should directed to "Previous Assessments"page', null, { dbPage }); 
  });

  test('Verify user is able to directed to subscription plans successfully', async ({ Given, dbPage, When, Then }) => { 
    await Given('The user is on the dashboard', null, { dbPage }); 
    await When('The user clicks User profile icon and clicks subscription plans option', null, { dbPage }); 
    await Then('The user should directed to "subscription plans"page', null, { dbPage }); 
  });

});

// == technical section ==

test.use({
  $test: ({}, use) => use(test),
  $uri: ({}, use) => use('feature\\Dashboard.feature'),
  $bddFileData: ({}, use) => use(bddFileData),
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":15,"pickleLine":12,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user navigates to the login page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When user clicks the sign in button on the homepage","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When user fills the username field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When the user fills the password field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":11,"gherkinStepLine":8,"keywordType":"Action","textWithKeyword":"When the user clicks the login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":12,"gherkinStepLine":9,"keywordType":"Outcome","textWithKeyword":"Then the user should be logged in successfully","isBg":true,"stepMatchArguments":[]},{"pwStepLine":16,"gherkinStepLine":13,"keywordType":"Context","textWithKeyword":"Given the user should be logged in successfully","stepMatchArguments":[]},{"pwStepLine":17,"gherkinStepLine":14,"keywordType":"Action","textWithKeyword":"When The user is directed to the dashboard URL","stepMatchArguments":[]},{"pwStepLine":18,"gherkinStepLine":15,"keywordType":"Outcome","textWithKeyword":"Then The page should have URL visible","stepMatchArguments":[]}]},
  {"pwTestLine":21,"pickleLine":17,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user navigates to the login page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When user clicks the sign in button on the homepage","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When user fills the username field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When the user fills the password field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":11,"gherkinStepLine":8,"keywordType":"Action","textWithKeyword":"When the user clicks the login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":12,"gherkinStepLine":9,"keywordType":"Outcome","textWithKeyword":"Then the user should be logged in successfully","isBg":true,"stepMatchArguments":[]},{"pwStepLine":22,"gherkinStepLine":18,"keywordType":"Context","textWithKeyword":"Given The user is on the dashboard","stepMatchArguments":[]},{"pwStepLine":23,"gherkinStepLine":19,"keywordType":"Action","textWithKeyword":"When The user clicks on the \"Start New Assessment\" button","stepMatchArguments":[{"group":{"start":23,"value":"\"Start New Assessment\"","children":[{"start":24,"value":"Start New Assessment","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":24,"gherkinStepLine":20,"keywordType":"Outcome","textWithKeyword":"Then the user should be logged in successfully","stepMatchArguments":[]}]},
  {"pwTestLine":27,"pickleLine":22,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user navigates to the login page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When user clicks the sign in button on the homepage","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When user fills the username field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When the user fills the password field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":11,"gherkinStepLine":8,"keywordType":"Action","textWithKeyword":"When the user clicks the login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":12,"gherkinStepLine":9,"keywordType":"Outcome","textWithKeyword":"Then the user should be logged in successfully","isBg":true,"stepMatchArguments":[]},{"pwStepLine":28,"gherkinStepLine":23,"keywordType":"Context","textWithKeyword":"Given The user is on the dashboard","stepMatchArguments":[]},{"pwStepLine":29,"gherkinStepLine":24,"keywordType":"Action","textWithKeyword":"When The user clicks the \"View Previous Assessments\" button","stepMatchArguments":[{"group":{"start":20,"value":"\"View Previous Assessments\"","children":[{"start":21,"value":"View Previous Assessments","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":30,"gherkinStepLine":25,"keywordType":"Outcome","textWithKeyword":"Then The user should be in \"View Previous Assessments\" page","stepMatchArguments":[{"group":{"start":22,"value":"\"View Previous Assessments\"","children":[{"start":23,"value":"View Previous Assessments","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":33,"pickleLine":27,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user navigates to the login page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When user clicks the sign in button on the homepage","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When user fills the username field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When the user fills the password field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":11,"gherkinStepLine":8,"keywordType":"Action","textWithKeyword":"When the user clicks the login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":12,"gherkinStepLine":9,"keywordType":"Outcome","textWithKeyword":"Then the user should be logged in successfully","isBg":true,"stepMatchArguments":[]},{"pwStepLine":34,"gherkinStepLine":28,"keywordType":"Context","textWithKeyword":"Given The user is on the dashboard","stepMatchArguments":[]},{"pwStepLine":35,"gherkinStepLine":29,"keywordType":"Action","textWithKeyword":"When dashboard is displayed with 'AI analysis usage'","stepMatchArguments":[{"group":{"start":28,"value":"'AI analysis usage'","children":[{"children":[{"children":[]}]},{"start":29,"value":"AI analysis usage","children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":36,"gherkinStepLine":30,"keywordType":"Outcome","textWithKeyword":"Then The page should have URL visible","stepMatchArguments":[]}]},
  {"pwTestLine":39,"pickleLine":32,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user navigates to the login page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When user clicks the sign in button on the homepage","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When user fills the username field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When the user fills the password field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":11,"gherkinStepLine":8,"keywordType":"Action","textWithKeyword":"When the user clicks the login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":12,"gherkinStepLine":9,"keywordType":"Outcome","textWithKeyword":"Then the user should be logged in successfully","isBg":true,"stepMatchArguments":[]},{"pwStepLine":40,"gherkinStepLine":33,"keywordType":"Context","textWithKeyword":"Given The user is on the dashboard","stepMatchArguments":[]},{"pwStepLine":41,"gherkinStepLine":34,"keywordType":"Action","textWithKeyword":"When verify user is able click on 'upgrade to premium' button","stepMatchArguments":[{"group":{"start":29,"value":"'upgrade to premium'","children":[{"children":[{"children":[]}]},{"start":30,"value":"upgrade to premium","children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":42,"gherkinStepLine":35,"keywordType":"Outcome","textWithKeyword":"Then user is on subscription page","stepMatchArguments":[]}]},
  {"pwTestLine":45,"pickleLine":38,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user navigates to the login page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When user clicks the sign in button on the homepage","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When user fills the username field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When the user fills the password field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":11,"gherkinStepLine":8,"keywordType":"Action","textWithKeyword":"When the user clicks the login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":12,"gherkinStepLine":9,"keywordType":"Outcome","textWithKeyword":"Then the user should be logged in successfully","isBg":true,"stepMatchArguments":[]},{"pwStepLine":46,"gherkinStepLine":39,"keywordType":"Context","textWithKeyword":"Given The user is on the dashboard","stepMatchArguments":[]},{"pwStepLine":47,"gherkinStepLine":40,"keywordType":"Action","textWithKeyword":"When The user clicks on  the Start your first assessment button","stepMatchArguments":[]},{"pwStepLine":48,"gherkinStepLine":41,"keywordType":"Outcome","textWithKeyword":"Then the user should be logged in successfully","stepMatchArguments":[]}]},
  {"pwTestLine":51,"pickleLine":43,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user navigates to the login page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When user clicks the sign in button on the homepage","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When user fills the username field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When the user fills the password field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":11,"gherkinStepLine":8,"keywordType":"Action","textWithKeyword":"When the user clicks the login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":12,"gherkinStepLine":9,"keywordType":"Outcome","textWithKeyword":"Then the user should be logged in successfully","isBg":true,"stepMatchArguments":[]},{"pwStepLine":52,"gherkinStepLine":44,"keywordType":"Context","textWithKeyword":"Given The user is on the dashboard","stepMatchArguments":[]},{"pwStepLine":53,"gherkinStepLine":45,"keywordType":"Action","textWithKeyword":"When The user clicks on Update settings under the Account Settings section","stepMatchArguments":[]},{"pwStepLine":54,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"Then The user should directed to Account Settings page","stepMatchArguments":[]}]},
  {"pwTestLine":57,"pickleLine":48,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user navigates to the login page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When user clicks the sign in button on the homepage","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When user fills the username field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When the user fills the password field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":11,"gherkinStepLine":8,"keywordType":"Action","textWithKeyword":"When the user clicks the login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":12,"gherkinStepLine":9,"keywordType":"Outcome","textWithKeyword":"Then the user should be logged in successfully","isBg":true,"stepMatchArguments":[]},{"pwStepLine":58,"gherkinStepLine":49,"keywordType":"Context","textWithKeyword":"Given The user is on the dashboard","stepMatchArguments":[]},{"pwStepLine":59,"gherkinStepLine":50,"keywordType":"Action","textWithKeyword":"When The user clicks on Upgrade now  section   in the Subscription Plans section","stepMatchArguments":[]},{"pwStepLine":60,"gherkinStepLine":51,"keywordType":"Outcome","textWithKeyword":"Then user is on subscription page","stepMatchArguments":[]}]},
  {"pwTestLine":63,"pickleLine":54,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user navigates to the login page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When user clicks the sign in button on the homepage","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When user fills the username field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When the user fills the password field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":11,"gherkinStepLine":8,"keywordType":"Action","textWithKeyword":"When the user clicks the login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":12,"gherkinStepLine":9,"keywordType":"Outcome","textWithKeyword":"Then the user should be logged in successfully","isBg":true,"stepMatchArguments":[]},{"pwStepLine":64,"gherkinStepLine":55,"keywordType":"Context","textWithKeyword":"Given The user is on the dashboard","stepMatchArguments":[]},{"pwStepLine":65,"gherkinStepLine":56,"keywordType":"Action","textWithKeyword":"When The user clicks on View history  section in the Assessment History section","stepMatchArguments":[]},{"pwStepLine":66,"gherkinStepLine":57,"keywordType":"Outcome","textWithKeyword":"Then The user should be in \"View Previous Assessments\" page","stepMatchArguments":[{"group":{"start":22,"value":"\"View Previous Assessments\"","children":[{"start":23,"value":"View Previous Assessments","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":69,"pickleLine":59,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user navigates to the login page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When user clicks the sign in button on the homepage","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When user fills the username field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When the user fills the password field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":11,"gherkinStepLine":8,"keywordType":"Action","textWithKeyword":"When the user clicks the login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":12,"gherkinStepLine":9,"keywordType":"Outcome","textWithKeyword":"Then the user should be logged in successfully","isBg":true,"stepMatchArguments":[]},{"pwStepLine":70,"gherkinStepLine":60,"keywordType":"Context","textWithKeyword":"Given The user is on the dashboard","stepMatchArguments":[]},{"pwStepLine":71,"gherkinStepLine":61,"keywordType":"Action","textWithKeyword":"When The user clicks on \"About Us  \"section   in the \"company\" section","stepMatchArguments":[{"group":{"start":48,"value":"\"company\"","children":[{"start":49,"value":"company","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":72,"gherkinStepLine":62,"keywordType":"Outcome","textWithKeyword":"Then The user should directed to \"About Us \"page","stepMatchArguments":[]}]},
  {"pwTestLine":75,"pickleLine":64,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user navigates to the login page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When user clicks the sign in button on the homepage","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When user fills the username field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When the user fills the password field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":11,"gherkinStepLine":8,"keywordType":"Action","textWithKeyword":"When the user clicks the login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":12,"gherkinStepLine":9,"keywordType":"Outcome","textWithKeyword":"Then the user should be logged in successfully","isBg":true,"stepMatchArguments":[]},{"pwStepLine":76,"gherkinStepLine":65,"keywordType":"Context","textWithKeyword":"Given The user is on the dashboard","stepMatchArguments":[]},{"pwStepLine":77,"gherkinStepLine":66,"keywordType":"Action","textWithKeyword":"When The user clicks on \"Blog  \"section   in the \"company\" section","stepMatchArguments":[{"group":{"start":44,"value":"\"company\"","children":[{"start":45,"value":"company","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":78,"gherkinStepLine":67,"keywordType":"Outcome","textWithKeyword":"Then The user should directed to \"Blog\"page","stepMatchArguments":[]}]},
  {"pwTestLine":81,"pickleLine":69,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user navigates to the login page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When user clicks the sign in button on the homepage","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When user fills the username field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When the user fills the password field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":11,"gherkinStepLine":8,"keywordType":"Action","textWithKeyword":"When the user clicks the login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":12,"gherkinStepLine":9,"keywordType":"Outcome","textWithKeyword":"Then the user should be logged in successfully","isBg":true,"stepMatchArguments":[]},{"pwStepLine":82,"gherkinStepLine":70,"keywordType":"Context","textWithKeyword":"Given The user is on the dashboard","stepMatchArguments":[]},{"pwStepLine":83,"gherkinStepLine":71,"keywordType":"Action","textWithKeyword":"When The user clicks on \"Contact Us  \"section   in the \"company\" section","stepMatchArguments":[{"group":{"start":50,"value":"\"company\"","children":[{"start":51,"value":"company","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":84,"gherkinStepLine":72,"keywordType":"Outcome","textWithKeyword":"Then The user should directed to \"Contact Us\"page","stepMatchArguments":[]}]},
  {"pwTestLine":87,"pickleLine":74,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user navigates to the login page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When user clicks the sign in button on the homepage","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When user fills the username field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When the user fills the password field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":11,"gherkinStepLine":8,"keywordType":"Action","textWithKeyword":"When the user clicks the login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":12,"gherkinStepLine":9,"keywordType":"Outcome","textWithKeyword":"Then the user should be logged in successfully","isBg":true,"stepMatchArguments":[]},{"pwStepLine":88,"gherkinStepLine":75,"keywordType":"Context","textWithKeyword":"Given The user is on the dashboard","stepMatchArguments":[]},{"pwStepLine":89,"gherkinStepLine":76,"keywordType":"Action","textWithKeyword":"When The user clicks on \"Terms \"section   in the \"© 2025 Manan - Medical Triage Assistant\" section","stepMatchArguments":[{"group":{"start":26,"value":"\"section   in the \"","children":[{"start":27,"value":"section   in the ","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":47,"value":"2025","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":90,"gherkinStepLine":77,"keywordType":"Outcome","textWithKeyword":"Then The user should directed to \"Terms\"page","stepMatchArguments":[]}]},
  {"pwTestLine":93,"pickleLine":79,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user navigates to the login page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When user clicks the sign in button on the homepage","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When user fills the username field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When the user fills the password field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":11,"gherkinStepLine":8,"keywordType":"Action","textWithKeyword":"When the user clicks the login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":12,"gherkinStepLine":9,"keywordType":"Outcome","textWithKeyword":"Then the user should be logged in successfully","isBg":true,"stepMatchArguments":[]},{"pwStepLine":94,"gherkinStepLine":80,"keywordType":"Context","textWithKeyword":"Given The user is on the dashboard","stepMatchArguments":[]},{"pwStepLine":95,"gherkinStepLine":81,"keywordType":"Action","textWithKeyword":"When The user clicks on \"Privacy \"section   in the \"© 2025 Manan - Medical Triage Assistant\" section","stepMatchArguments":[{"group":{"start":28,"value":"\"section   in the \"","children":[{"start":29,"value":"section   in the ","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":49,"value":"2025","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":96,"gherkinStepLine":82,"keywordType":"Outcome","textWithKeyword":"Then The user should directed to \"Privacy\"page","stepMatchArguments":[]}]},
  {"pwTestLine":99,"pickleLine":84,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user navigates to the login page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When user clicks the sign in button on the homepage","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When user fills the username field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When the user fills the password field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":11,"gherkinStepLine":8,"keywordType":"Action","textWithKeyword":"When the user clicks the login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":12,"gherkinStepLine":9,"keywordType":"Outcome","textWithKeyword":"Then the user should be logged in successfully","isBg":true,"stepMatchArguments":[]},{"pwStepLine":100,"gherkinStepLine":85,"keywordType":"Context","textWithKeyword":"Given The user is on the dashboard","stepMatchArguments":[]},{"pwStepLine":101,"gherkinStepLine":86,"keywordType":"Action","textWithKeyword":"When The user clicks User profile icon and clicks Logout option","stepMatchArguments":[]},{"pwStepLine":102,"gherkinStepLine":87,"keywordType":"Outcome","textWithKeyword":"Then The user should get \"Session Ended\" message and rediected to Manan signin Page","stepMatchArguments":[{"group":{"start":20,"value":"\"Session Ended\"","children":[{"start":21,"value":"Session Ended","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":105,"pickleLine":89,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user navigates to the login page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When user clicks the sign in button on the homepage","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When user fills the username field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When the user fills the password field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":11,"gherkinStepLine":8,"keywordType":"Action","textWithKeyword":"When the user clicks the login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":12,"gherkinStepLine":9,"keywordType":"Outcome","textWithKeyword":"Then the user should be logged in successfully","isBg":true,"stepMatchArguments":[]},{"pwStepLine":106,"gherkinStepLine":90,"keywordType":"Context","textWithKeyword":"Given The user is on the dashboard","stepMatchArguments":[]},{"pwStepLine":107,"gherkinStepLine":91,"keywordType":"Action","textWithKeyword":"When The user clicks User profile icon and clicks  settings option","stepMatchArguments":[]},{"pwStepLine":108,"gherkinStepLine":92,"keywordType":"Outcome","textWithKeyword":"Then The user should directed to \"settings\"page","stepMatchArguments":[]}]},
  {"pwTestLine":111,"pickleLine":94,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user navigates to the login page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When user clicks the sign in button on the homepage","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When user fills the username field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When the user fills the password field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":11,"gherkinStepLine":8,"keywordType":"Action","textWithKeyword":"When the user clicks the login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":12,"gherkinStepLine":9,"keywordType":"Outcome","textWithKeyword":"Then the user should be logged in successfully","isBg":true,"stepMatchArguments":[]},{"pwStepLine":112,"gherkinStepLine":95,"keywordType":"Context","textWithKeyword":"Given The user is on the dashboard","stepMatchArguments":[]},{"pwStepLine":113,"gherkinStepLine":96,"keywordType":"Action","textWithKeyword":"When The user clicks User profile icon and clicks previous assessment option","stepMatchArguments":[]},{"pwStepLine":114,"gherkinStepLine":97,"keywordType":"Outcome","textWithKeyword":"Then The user should directed to \"Previous Assessments\"page","stepMatchArguments":[]}]},
  {"pwTestLine":117,"pickleLine":99,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given user navigates to the login page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When user clicks the sign in button on the homepage","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When user fills the username field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When the user fills the password field with credentials from env","isBg":true,"stepMatchArguments":[]},{"pwStepLine":11,"gherkinStepLine":8,"keywordType":"Action","textWithKeyword":"When the user clicks the login button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":12,"gherkinStepLine":9,"keywordType":"Outcome","textWithKeyword":"Then the user should be logged in successfully","isBg":true,"stepMatchArguments":[]},{"pwStepLine":118,"gherkinStepLine":100,"keywordType":"Context","textWithKeyword":"Given The user is on the dashboard","stepMatchArguments":[]},{"pwStepLine":119,"gherkinStepLine":101,"keywordType":"Action","textWithKeyword":"When The user clicks User profile icon and clicks subscription plans option","stepMatchArguments":[]},{"pwStepLine":120,"gherkinStepLine":102,"keywordType":"Outcome","textWithKeyword":"Then The user should directed to \"subscription plans\"page","stepMatchArguments":[]}]},
]; // bdd-data-end